export default {
  login: 'ChangJuneKim',
  id: 77381154,
  node_id: 'MDQ6VXNlcjc3MzgxMTU0',
  avatar_url: 'https://avatars.githubusercontent.com/u/77381154?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/ChangJuneKim',
  html_url: 'https://github.com/ChangJuneKim',
  followers_url: 'https://api.github.com/users/ChangJuneKim/followers',
  following_url: 'https://api.github.com/users/ChangJuneKim/following{/other_user}',
  gists_url: 'https://api.github.com/users/ChangJuneKim/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/ChangJuneKim/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/ChangJuneKim/subscriptions',
  organizations_url: 'https://api.github.com/users/ChangJuneKim/orgs',
  repos_url: 'https://api.github.com/users/ChangJuneKim/repos',
  events_url: 'https://api.github.com/users/ChangJuneKim/events{/privacy}',
  received_events_url: 'https://api.github.com/users/ChangJuneKim/received_events',
  type: 'User',
  site_admin: false,
  name: '김창준',
  company: 'Out of work',
  blog: 'https://window6kim.tistory.com/',
  location: 'Miryang, Republic of Korea',
  email: null,
  hireable: null,
  bio: '화이팅화이팅',
  twitter_username: null,
  public_repos: 8,
  public_gists: 1,
  followers: 0,
  following: 3,
  created_at: '2021-01-13T08:01:57Z',
  updated_at: '2022-02-19T14:52:02Z',
};
